### ISSUE TITLE
IOS编译失败

### ISSUE THREAD

**Issue by lantongxue** [rhymelph/r_upgrade#10]
fatal error: 'r_upgrade/r_upgrade-Swift.h' file not found
    #import <r_upgrade/r_upgrade-Swift.h>

按照 #5 这个issue里面的方法操作了，没用

**Comment by lantongxue** [comment]
很奇怪，突然又好了

**Comment by Karthus1110** [comment]
@rhymelph  我也是同上 但是还是编译不了 试过了#5中的方法

**Comment by rhymelph** [comment]
检查flutter版本，并保持最新

**Comment by Karthus1110** [comment]
![image](https://user-images.githubusercontent.com/13864988/81526672-d403a500-938a-11ea-8fb2-e46aae69144e.png)

已更新 仍然报错
@rhymelph

**Comment by rhymelph** [comment]
@Karthus1110 你的工程项目用什么写的OC还是swift？

**Comment by Karthus1110** [comment]
是flutter自己生成的，没有修改过

**Comment by rhymelph** [comment]
?

**Comment by Karthus1110** [comment]
OC

**Comment by rhymelph** [comment]
如果没有特别要求，在项目目录下运行
flutter create .
把项目转为swfit即可。
因为该插件使用swift写的
