### ISSUE TITLE
请问权限配置完了，通过URL还是会报权限异常怎么回事

### ISSUE THREAD

**Issue by superwei629** [rhymelph/r_upgrade#11]
![111](https://user-images.githubusercontent.com/51434982/83001119-df6af780-a03d-11ea-9b0f-e43f6d52caee.png)
点击下载（非安装）之后，会出现异常
![222](https://user-images.githubusercontent.com/51434982/83001320-28bb4700-a03e-11ea-83df-69314569d296.png)

**Comment by rhymelph** [comment]
没有动态申请权限，用permission_handler申请

**Comment by superwei629** [comment]
![444](https://user-images.githubusercontent.com/51434982/83004295-104d2b80-a042-11ea-8f0a-193f147dcc00.png)
有申请个，根据例子来写的

**Comment by superwei629** [comment]
没有提示更新失败，打包好的文件没提示进度条不加载，模拟器上升级看控制台输出是没有权限

**Comment by superwei629** [comment]
会请求存储权限，通过之后，还是提示没权限

**Comment by rhymelph** [comment]
权限的问题，设备版本os版本过高，或permission_handle5.0申请试一下，或到permisson_handle仓库下提issue------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;summer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月27日(星期三) 下午5:48
收件人:&nbsp;&quot;rhymelph/r_upgrade&quot;<r_upgrade@noreply.github.com&gt;;
抄送:&nbsp;&quot;PengHui Li&quot;<708959817@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [rhymelph/r_upgrade] 请问权限配置完了，通过URL还是会报权限异常怎么回事 (#11)

**Comment by superwei629** [comment]
permission_handle5.0也无法使用
在后台app权限设置“应用内安装其他应用”点击允许，则可以下载安装成功

**Comment by rhymelph** [comment]
你的os是什么版本？

**Comment by superwei629** [comment]
android10

**Comment by superwei629** [comment]
请问是和版本有关系吗

**Comment by rhymelph** [comment]
没有测出这个问题

**Comment by superwei629** [comment]
![333](https://user-images.githubusercontent.com/51434982/83107549-10583480-a0f1-11ea-8446-ca547d0de4e7.jpg)

我配置了    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
但是实际在安装过程中只显示了两个权限，感觉是这个问题，请问怎么解决呢

**Comment by rhymelph** [comment]
不太清楚你的情况
