### ISSUE TITLE
build apk failed

### ISSUE THREAD

**Issue by ZMNOTZ** [rhymelph/r_upgrade#16]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/emery/.pub-cache/hosted/pub.flutter-io.cn/r_upgrade-0.3.1/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'r_upgrade'.
> Project with path ':r_upgrade' could not be found in root project 'r_upgrade'.

**Comment by rhymelph** [comment]
Duplicate of #40
