### ISSUE TITLE
修改进度条提示成中文遇到一些问题，

### ISSUE THREAD

**Issue by IcePigZDB** [rhymelph/r_upgrade#18]
*  flutter doctor
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.21.0-10.0.pre.159, on Microsoft Windows [Version 10.0.18362.1016], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)
```
*  pubspec.yml
```yaml
  r_upgrade: ^0.3.1
```
* 调用
```dart
    int id = await RUpgrade.upgrade('http://$ip/1.apk',
        fileName: '1.apk',
        isAutoRequestInstall: true,
        notificationStyle: NotificationStyle.speechAndPlanTime);
```
* 配置文件
文档上写的是`project/android/app/main/res/r_upgrade_value.xml`，我的flutter项目没有这个文件夹路径，在`project/android/app/main/res/r_upgrade_value.xml`以及`project/android/app/src/main/res/r_upgrade_value.xml`都新建了配置文件。
![image](https://user-images.githubusercontent.com/39407623/91191052-e1208600-e726-11ea-9cb8-6175990c261b.png)
实际跑之后任务栏显示的还是英文版本`100kb/s 300s left`
![image](https://user-images.githubusercontent.com/39407623/91191559-85a2c800-e727-11ea-93c0-e0476dc3f18d.png)
想请教一下各位走过路过的大佬赐教一下我哪里配错了= =感谢。

**Comment by rhymelph** [comment]
project/android/app/main/res/values/r_upgrade_value.xml

**Comment by IcePigZDB** [comment]
可以了，感谢大佬提供这么好用的包！我这项目里面多个src ： project/android/app/`src`/main/res/values/r_upgrade_value.xml
![image](https://user-images.githubusercontent.com/39407623/91246200-d6dfa580-e781-11ea-8ca3-3721084a9dc3.png)
