### ISSUE TITLE
Android个别手机下载提示Download Faild 重新卸载后，再安装更新下载还是一样。

### ISSUE THREAD

**Issue by helloWorldGeorge** [rhymelph/r_upgrade#19]
机型：华为P30。
下载地址：http://image.danews.cc/upload/app/app-release.apk
报错截图:http://img.danews.cc/upload/ajax/20200831/a74438cb8b82769b04357f89c597eec9.png
我查看了APP权限，有存储权限，和正常能下载的手机都一样的权限。
重新下载老版本，再按提示语安装的话也是一样。

**Comment by rhymelph** [comment]
提供一下代码，日志信息，你是想解决问题还是说想证明有问题？

**Comment by helloWorldGeorge** [comment]
好的，这个手机是老板的手机，所以可能暂时不好抓日志，我这边自己也复现一下，抓到日志后，再来提交.之前确实不知道需要提供的信息是什么。
