### ISSUE TITLE
IOS编译报错，急急急

### ISSUE THREAD

**Issue by Gaoxichao** [rhymelph/r_upgrade#2]
提示：

 - `r_upgrade` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

这个好像是要作者你添加各配置

作者微信多少？

**Comment by rhymelph** [comment]
0.1.4
