### ISSUE TITLE
当下载被暂停，再继续下载，apk安装时会报无法解析的错误

### ISSUE THREAD

**Issue by Chen-Yong-Jie** [rhymelph/r_upgrade#22]
![3bbf760a12fcfb215a8e277c8f92336](https://user-images.githubusercontent.com/52515060/99368549-3ae3b700-28f6-11eb-9c32-cd8363fa33d9.jpg)

如果暂时无法解决此问题，有办法能禁用暂停吗，

**Comment by rhymelph** [comment]
v0.3.2
