### ISSUE TITLE
Security issue needs your help during Google Store's reviewing

### ISSUE THREAD

**Issue by Gavin-22** [rhymelph/r_upgrade#23]
Hello, 
  It's great to have r_upgrade rich APIs on APP upgrading.  It's the best solution I found. 
  But it's pity we have to remove it before since there's security issue on unsafe implementation of the X509TrustManager interface with the Apache HTTP client during Google Store's reviewing. 
  More information will be provided as below. May I know whether you will fix this issue ?  Thanks !

 ---------------------------
"Your application has a security issue because it uses a potentially unsafe implementation of the X509TrustManager interface with the Apache HTTP client. For more information and the date by which the vulnerability should be addressed, see this Google Help Center article.
Classes with vulnerabilities:
• com.example.r_upgrade.common.UpgradeService$b
----------------------------------

**Comment by Gavin-22** [comment]
Check your codes and it seems X509TrustManager has not been used. Please check whether to update new version for r_upgrade. 

private static class MyX509TrustManager implements X509TrustManager {

        // 检查客户端证书
        public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        }

        // 检查服务器端证书
        public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
        }

        // 返回受信任的X509证书数组
        public X509Certificate[] getAcceptedIssuers() {
            return null;
        }
    }

**Comment by rhymelph** [comment]
Update new version (0.3.2+1)
Have a nice day.

**Comment by Gavin-22** [comment]
你好，Penghui，
  https://pub.flutter-io.cn/packages/r_upgrade/install 这个里面还是r_upgrade: ^0.3.2。
帮忙更新一下呗？谢谢啊！

BR,
Gavin

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: PengHui Li<mailto:notifications@github.com>
发送时间: 2020年12月1日 15:40
收件人: rhymelph/r_upgrade<mailto:r_upgrade@noreply.github.com>
抄送: Gavin-22<mailto:gavin_22@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [rhymelph/r_upgrade] Security issue needs your help during Google Store's reviewing (#23)


Update new version (0.3.2+1)
Have a nice day.

―

**Comment by Gavin-22** [comment]
import javax.net.ssl.X509TrustManager; 

--> Please also help to delete this codes . :-) 

Could you update https://pub.flutter-io.cn/packages/r_upgrade/install  ? 
Thanks !

**Comment by rhymelph** [comment]
It has been updated. You can see it

**Comment by Gavin-22** [comment]
Thank you very much for your prompt changing !

**Comment by rhymelph** [comment]
v0.3.2+2

**Comment by Gavin-22** [comment]
Thanks, could you also update https://pub.flutter-io.cn/packages/r_upgrade/install ?

**Comment by rhymelph** [comment]
https://pub.flutter-io.cn/packages/r_upgrade/versions

**Comment by Gavin-22** [comment]
Thanks, it's availble now. :-)

**Comment by rhymelph** [comment]
#30
