### ISSUE TITLE
Any API to get new version available or not from Google Store ? 

### ISSUE THREAD

**Issue by Gavin-22** [rhymelph/r_upgrade#24]
Hi, 
  Appreciated for your working on r_upgrade and it's really helpful ! 
  Full of features but I have only 1 question maybe I'm wrong since I'm new to APP world. 

  It's good to have getVersionFromAppStore to notify users new version on Apple Store. 
  Is there any API for Google Store ? 

  Thank you in advance for your feedback !

**Comment by rhymelph** [comment]
It's a great idea. I'll add it in the future. Please keep following

**Comment by Gavin-22** [comment]
Will follow ! 

Is it possible to work for Huawei Store with new version nofitication too ? 
Thank you sincerely !

**Comment by rhymelph** [comment]
Of course,
