### ISSUE TITLE
android Q 下，报权限错误

### ISSUE THREAD

**Issue by dydysy** [rhymelph/r_upgrade#25]
W/System.err(32263): java.io.FileNotFoundException: /storage/emulated/0/Download/app-release.apk: open failed: EACCES (Permission denied)

在 安卓8.1 下的系统下，能正常使用。

**Comment by rhymelph** [comment]
目前没有添加target 为 29 ，请检查androidmanifest.xml 文件配置，已更新 v0.3.2+3 版本

**Comment by dydysy** [comment]
感谢提供更新。
