### ISSUE TITLE
run for ios error

### ISSUE THREAD

**Issue by hzysunrain** [rhymelph/r_upgrade#26]
1 warning generated.
   ~/.pub-cache/hosted/pub.flutter-io.cn/r_upgrade-0.3.2+3/ios/Classes/RUpgradePlugin.m:2:9: fatal error: 'r_upgrade/r_upgrade-Swift.h' file not found
    #import <r_upgrade/r_upgrade-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by hzysunrain** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)

**Comment by rhymelph** [comment]
try to  run `flutter clean` -> `cd ios` -> `pod install --repo-update` -> `cd ..` -> repeat

Still not ?

welcome to back feedback to this issues.

**Comment by hzysunrain** [comment]
update podfile file:

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

then run flutter clean -> cd ios -> pod install 

that's ok!
