### ISSUE TITLE
下载出现问题

### ISSUE THREAD

**Issue by LastMonopoly** [rhymelph/r_upgrade#29]
`example project` release 版本 总是显示 `下载失败`
我的flutter版本 1.22.5

**Comment by rhymelph** [comment]
请提供测试机型，网络状态，是否开启代理等信息

**Comment by LastMonopoly** [comment]
谢谢回复，我这边的华为和红米手机 测试的时候 都能`下载成功`，release版本都显示`下载失败`

**Comment by rhymelph** [comment]
AndroidManifest.xml 自行添加网络权限即可
