### ISSUE TITLE
WIFI网络断开报错，Android11，RedMi K30i，网络恢复下载没有自动恢复，求助大佬！

### ISSUE THREAD

**Issue by BrianChanGT** [rhymelph/r_upgrade#32]
I/flutter (25524): 34.31--DownloadStatus(2)
W/System.err(25524): java.net.SocketException: Software caused connection abort
W/System.err(25524):    at java.net.SocketInputStream.socketRead0(Native Method)
W/System.err(25524):    at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
W/System.err(25524):    at java.net.SocketInputStream.read(SocketInputStream.java:176)
W/System.err(25524):    at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/System.err(25524):    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
W/System.err(25524):    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
W/System.err(25524):    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
W/System.err(25524):    at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
W/System.err(25524):    at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/System.err(25524):    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/System.err(25524):    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err(25524):    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
W/System.err(25524):    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
W/System.err(25524):    at java.io.InputStream.read(InputStream.java:101)
W/System.err(25524):    at com.example.r_upgrade.common.UpgradeService$UpgradeRunnable.run(UpgradeService.java:492)
W/System.err(25524):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(25524):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(25524):    at java.lang.Thread.run(Thread.java:923)
D/r_upgrade.Service(25524): handlerDownloadFailure: failure
I/flutter (25524): 0.0--DownloadStatus(4)

**Comment by rhymelph** [comment]
fixed in v0.3.4
