### ISSUE TITLE
一直在获取资源

### ISSUE THREAD

**Issue by kinmoLun** [rhymelph/r_upgrade#4]
如题，坐等大佬解决。

**Comment by rhymelph** [comment]
试试换一个链接

**Comment by kinmoLun** [comment]
> 试试换一个链接

换过了，也不行，能否加Q交流：3222039032

**Comment by kinmoLun** [comment]
> 试试换一个链接

用你的demo，换链接也不行。

**Comment by rhymelph** [comment]
android版本6.0以上有获取访问文件的权限嘛？

**Comment by kinmoLun** [comment]
> android版本6.0以上有获取访问文件的权限嘛？

有的

**Comment by rhymelph** [comment]
https://pub.dev/packages/permission_handler 结合这个插件使用哦

**Comment by kinmoLun** [comment]
> https://pub.dev/packages/permission_handler 结合这个插件使用哦

嗯呢，用你的demo试过，也不行呢。

**Comment by rhymelph** [comment]
加个好友吧
