### ISSUE TITLE
提一个bug及解决方案.关于跳转ios 应用商店某些app闪退问题

### ISSUE THREAD

**Issue by miaozhenkun** [rhymelph/r_upgrade#41]
提一个 bug,  看了作者ios 插件代码, 
//获取应用信息 
getInfoFromAppStore
let appUrl = "https://itunes.apple.com/lookup?id=" + appId  没什么问题，但仅仅上架中国的APP 会查不到数据，应使用 
let appUrl = "https://itunes.apple.com/cn/lookup?id=" + appId  代替这行代码。

已测试，不影响使用
let appUrl = "https://itunes.apple.com/cn/lookup?id=414478124 可以查到数据

**Comment by rhymelph** [comment]
v0.3.5
