### ISSUE TITLE
Android 12 FLAG_IMMUTABLE

### ISSUE THREAD

**Issue by XMitja** [rhymelph/r_upgrade#49]
FLAG_IMMUTABLE is missing for PendingIntent in UpgradeNotification.java:

E/AndroidRuntime(11658): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.example.r_upgrade.DOWNLOAD_STATUS flg=0x10 (has extras) } in com.example.r_upgrade.common.UpgradeManager$3@7fc8eed
E/AndroidRuntime(11658): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1689)
E/AndroidRuntime(11658): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(11658): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(11658): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11658): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(11658): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(11658): 	at android.app.ActivityThread.main(ActivityThread.java:7838)
E/AndroidRuntime(11658): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11658): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(11658): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(11658): Caused by: java.lang.IllegalArgumentException: [...]: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by rhymelph** [comment]
if you set android compile SDK version  = 31 , will crash.

**Comment by rhymelph** [comment]
upgrade packages version to 0.3.7 ,  this crash will be fixed
