### ISSUE TITLE
热更新不支持了？

### ISSUE THREAD

**Issue by justdoitgo** [rhymelph/r_upgrade#52]
bool isSuccess = await RUpgrade.hotUpgrade(id);
这个方法找不到呀

**Comment by rhymelph** [comment]
@justdoitgo  这个很久之前的版本了吧....

**Comment by rhymelph** [comment]
```dart
enum RUpgradeFlavor {
  normal, // full upgrade
  hotUpgrade, // hot upgrade
  incrementUpgrade, // increment upgrade
}
```
传到这里面
RUpgrade.upgrade(...)
安装的话正常调用 `install`  就行

**Comment by justdoitgo** [comment]
找到问题了，是打包flutter build apk，打包后的热更新不了，然后调试模式安装的可以热更新~

**Comment by 07ami** [comment]
> 找到问题了，是打包flutter build apk，打包后的热更新不了，然后调试模式安装的可以热更新~

怎么解决呢
