### ISSUE TITLE
求解决

### ISSUE THREAD

**Issue by ziyotko** [rhymelph/r_upgrade#55]
![image](https://user-images.githubusercontent.com/28377989/158167943-bd5a8ab2-f8ba-4130-af62-a4d25f7e841b.png)

**Comment by ziyotko** [comment]
出现这个问题是我在app目录下配置了华为的json文件，请问有办法解决吗
![WX20220315-102054](https://user-images.githubusercontent.com/28377989/158293069-bc7b53ce-5571-425a-be9e-871af7982061.png)

**Comment by rhymelph** [comment]
我刚测了,没有发现你遇到的问题

**Comment by rhymelph** [comment]
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.r_upgrade_example"
        minSdkVersion 19
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

**Comment by rhymelph** [comment]
看看是不是minSDKVersion 的问题
