### ISSUE TITLE
上架谷歌出现问题

### ISSUE THREAD

**Issue by lan2001** [rhymelph/r_upgrade#65]
应用包含不符合设备和网络滥用策略的内容。已确定应用使用违反规则的 r upgrade SDK 版本，包括从 Google Play 外部未知来源下载或安装应用程序的代码。
就算没有开启这个功能，引用了这个包就提示这个问题。

**Comment by buxiaojiong** [comment]
同一个问题 作者是弃坑了么？

**Comment by Liberations** [comment]
同遇到怎么整啊？

**Comment by LaoHuan** [comment]
一样。都被下架了
