### ISSUE TITLE
关于点击通知栏跳转的问题

### ISSUE THREAD

**Issue by zzzhhhhh001** [rhymelph/r_upgrade#67]
请问目前可以禁用或者自定义点击通知栏进行页面跳转么

**Comment by rhymelph** [comment]
目前没有这个计划

**Comment by zzzhhhhh001** [comment]
想问问代码中哪里是控制点击通知栏跳转的那
&nbsp;

---原始邮件---
发件人: "PengHui ***@***.***&gt;
发送时间: 2022年11月4日(周五) 上午10:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rhymelph/r_upgrade] 关于点击通知栏跳转的问题 (Issue #67)




 
目前没有这个计划

**Comment by rhymelph** [comment]
可以看一下这个类
https://github.com/rhymelph/r_upgrade/blob/master/android/src/main/java/com/example/r_upgrade/common/UpgradeNotification.java

**Comment by zzzhhhhh001** [comment]
请问0.3.8+2版本中的例子点击通知暂停下载是怎么设置可以做到那
&nbsp;

---原始邮件---
发件人: "PengHui ***@***.***&gt;
发送时间: 2022年11月4日(周五) 中午11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rhymelph/r_upgrade] 关于点击通知栏跳转的问题 (Issue #67)




 
可以看一下这个类
 https://github.com/rhymelph/r_upgrade/blob/master/android/src/main/java/com/example/r_upgrade/common/UpgradeNotification.java
