### ISSUE TITLE
There was a problem to parsing the package.

### ISSUE THREAD

**Issue by MohammadAliK** [rhymelph/r_upgrade#68]
**Basic Info:**

- Flutter/Dart SDK: Dart 2.18.0 + Flutter 3.3.5
- Null-safety enabled: No
- Reproducibility: Always
- OS: macOS 12.6 (Chip Apple M1 Pro)
- Device: Pixel 2 (OS Android 11) (API Level 29)

Code:
```
void upgrade() async {
    apkDownloadId = await RUpgrade.upgrade(
        'https://drive.google.com/file/d/1CyKTQp8Xx9KkL6LaFzGk3-fy8TeGUC91/view?usp=share_link',
        fileName: 'crm_hafooz_dev_19.apk',
        notificationVisibility: NotificationVisibility.VISIBILITY_VISIBLE,
        notificationStyle: NotificationStyle.planTimeAndSpeech,
        installType: RUpgradeInstallType.normal,
        useDownloadManager: false);
  }
```

**Error Message:**
There was a problem to parsing the package.

![image](https://user-images.githubusercontent.com/35557476/200764432-e965ee49-ef49-4f81-822b-1c78c0f597f8.png)

**Comment by rhymelph** [comment]
This download link is a website link.

**Comment by rhymelph** [comment]
https://drive.google.com/file/d/1CyKTQp8Xx9KkL6LaFzGk3-fy8TeGUC91/view?usp=share_linkThis download link is a website link.

**Comment by MohammadAliK** [comment]
Thanks @rhymelph
