### ISSUE TITLE
提示没有安装权限

### ISSUE THREAD

**Issue by JohnGuSir** [rhymelph/r_upgrade#83]
await RUpgrade.upgrade(url,
          notificationVisibility: NotificationVisibility.VISIBILITY_VISIBLE_NOTIFY_COMPLETED,
          fileName: _appName,
          notificationStyle: NotificationStyle.speechAndPlanTime);
          
          下载完成提示没有安装权限

**Comment by JohnGuSir** [comment]
r_upgrade: ^0.4.2

**Comment by JohnGuSir** [comment]
@rhymelph

**Comment by JohnGuSir** [comment]
没有报错，就是提示 没有权限安装

**Comment by JohnGuSir** [comment]
去手动打开未知来源安装 还是提示没有权限安装

**Comment by rhymelph** [comment]
去AndroidManifest 添加安装权限,具体可以看文档
