### ISSUE TITLE
增量更新闪退

### ISSUE THREAD

**Issue by yecaiyu1999** [rhymelph/r_upgrade#86]
在模拟器、PDA设备商测试没问题，小米手机（小米9pro 安卓系统11）下载完毕后直接闪退
执行日志如下：
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Mi9 Pro 5G in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:57738/aSRGxIlhsyw=/ws
I/TetheringManager( 5859): registerTetheringEventCallback:com.example.r_upgrade_example
D/r_upgrade.Service( 5859): onReceive: 当前网络正在连接
D/r_upgrade.Service( 5859): run: code=200
D/r_upgrade.Service( 5859): run: maxLength:10965266
D/r_upgrade.Service( 5859): handlerDownloadRunning: running queryTask: 下载中
D/r_upgrade.Service( 5859): url: http://192.168.64.34:8003/apk/patch.wgt
D/r_upgrade.Service( 5859): ============>total:10965266，progress:5031384，45.00% , 9484.71kb/s , 预计：1s
D/r_upgrade.Service( 5859): handlerDownloadRunning: running queryTask: 下载中
D/r_upgrade.Service( 5859): url: http://192.168.64.34:8003/apk/patch.wgt
D/r_upgrade.Service( 5859): ============>total:10965266，progress:10813248，98.27% , 11332.50kb/s , 预计：0s
D/r_upgrade.Service( 5859): handlerDownloadFinish: finish
D/r_upgrade.Increment( 5859): oldApck路径：/data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/base.apk
F/libc    ( 5859): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76d5a7efe8 in tid 5896 (AsyncTask #1), pid 5859 (upgrade_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/crux/crux:11/RKQ1.200826.002/V13.0.1.0.RFXCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-12-22 15:53:29+0800
pid: 5859, tid: 5896, name: AsyncTask #1  >>> com.example.r_upgrade_example <<<
uid: 10420
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76d5a7efe8
    x0  00000076d5a90a28  x1  0000000000010000  x2  0000000000000001  x3  00000076d5b6c0c0
    x4  00000076327d28a0  x5  00000076327d28c0  x6  00000076d5b6c040  x7  00000076d5b6c080
    x8  0000000000000000  x9  0000000000000002  x10 0000000000000001  x11 0000000000000000
    x12 00000076d5b6c060  x13 00000076d5b6c0a0  x14 00000076327d1550  x15 00000076327d1560
    x16 00000076d3a86930  x17 00000076d3a7b320  x18 00000075ddd6e000  x19 0000000000000000
    x20 00000076d3a8b944  x21 00000076d5a90a28  x22 0000000000000fff  x23 00000076d3a8b970
    x24 00000000000000f0  x25 000000000000000a  x26 000000000000076f  x27 00000076d3a8b000
    x28 00000076d5a7efe8  x29 000000763d905e60
    lr  00000076d3a7d7c0  sp  000000763d905e30  pc  00000076d5a7efe8  pst 0000000080000000
backtrace:
      #00 pc 0000000000000fe8  <anonymous:76d5a7e000>
      #01 pc 00000000000f77bc  /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+364) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
      #02 pc 00000000000f2574  /apex/com.android.runtime/lib64/bionic/libc.so (exit+24) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
      #03 pc 00000000000d652c  /apex/com.android.runtime/lib64/bionic/libc.so (verr+168) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
      #04 pc 00000000000d53a8  /apex/com.android.runtime/lib64/bionic/libc.so (err+100) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
      #05 pc 0000000000011b64  /data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/lib/arm64/libr_upgrade_lib.so (bspatch_main+2348) (BuildId: 9feedbad27c37ec2c661e89c6b1046493db71b74)
      #06 pc 0000000000010638  /data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/lib/arm64/libr_upgrade_lib.so (Java_com_example_r_1upgrade_1lib_RUpgradeLib_mixinPatch+156) (BuildId: 9feedbad27c37ec2c661e89c6b1046493db71b74)
      #07 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #08 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #09 pc 0000000000197e94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #10 pc 0000000000305328  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #11 pc 0000000000300440  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #12 pc 00000000006338f8  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+868) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #13 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #14 pc 00000000000078fe  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/base.apk!classes2.dex] (com.example.r_upgrade.common.manager.IncrementUpgradeManager.mixinAndGetNewApk+142)
      #15 pc 0000000000633b34  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1440) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #16 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #17 pc 000000000000976c  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/base.apk!classes2.dex] (com.example.r_upgrade.common.tasks.GenerateAndInstallAsyncTask.doInBackground+436)
      #18 pc 0000000000633b34  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1440) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #19 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #20 pc 00000000000098f0  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~aHX_HL9c5iY12ExfUrkiJA==/com.example.r_upgrade_example-pyQAbS9SfIuBaWD7gLZFIA==/base.apk!classes2.dex] (com.example.r_upgrade.common.tasks.GenerateAndInstallAsyncTask.doInBackground+4)
      #21 pc 0000000000633b34  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1440) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #22 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #23 pc 000000000037b18c  /system/framework/framework.jar (offset 0x92e000) (android.os.AsyncTask$3.call+40)
      #24 pc 00000000006354c8  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1840) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #25 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #26 pc 00000000001ef262  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.FutureTask.run+62)
      #27 pc 00000000006354c8  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1840) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #28 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #29 pc 000000000037b3c8  /system/framework/framework.jar (offset 0x92e000) (android.os.AsyncTask$SerialExecutor$1.run+4)
      #30 pc 00000000006354c8  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1840) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #31 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #32 pc 00000000001fa0b2  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor.runWorker+158)
      #33 pc 0000000000633b34  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1440) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #34 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #35 pc 00000000001f8e74  /apex/com.android.art/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run+4)
      #36 pc 00000000006354c8  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1840) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #37 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #38 pc 00000000000eb86c  /apex/com.android.art/javalib/core-oj.jar (java.lang.Thread.run+8)
      #39 pc 00000000002f7e1c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.9529414189519865523)+268) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #40 pc 000000000062250c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+796) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #41 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #42 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #43 pc 0000000000197e94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #44 pc 000000000052aefc  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #45 pc 000000000052c0fc  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+440) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #46 pc 0000000000579474  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1272) (BuildId: fb3bb09798b56b49f9a198b10862a495)
      #47 pc 00000000000f42e4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
      #48 pc 000000000008ec64  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 1000f0e49ba06da6dc5a4e8d210ba481)
Lost connection to device.

Exited.

**Comment by cjl1105173210** [comment]
有解决办法吗

**Comment by yecaiyu1999** [comment]
> 有解决办法吗

不晓得，目前采用全量更新+内置小程序实现热更新了，感觉应该是合并包有问题。
